name: Cloud Application Feature Branch Build

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup JDK 11
        uses: actions/setup-java@v2.3.1
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Build with maven
        run: ./mvnw -B test
